<a href="https://colab.research.google.com/github/CarineMS/UFV/blob/main/ELT572_U1A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Caderno de Exercícios Python


#### Capítulo 03 - Arranjos
#### Disciplina: Linguagens de Programação para Inteligência Artificial

**Aluna:** Carine Madeira Soares  
**Instituição:** Universidade Federal de Viçosa


In [7]:
import pandas as pd
import numpy as np

# https://numpy.org/doc/stable/index.html

### 3.1 Vetores

In [ ]:
notas = np.empty(5) # pode ter lixo na memória
notas

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
print('notas = ', notas)

notas =  [0.   0.25 0.5  0.75 1.  ]


In [ ]:
notas2 = np.zeros(5)
notas2

array([0., 0., 0., 0., 0.])

In [ ]:
print('notas 2 = ', notas2)

notas 2 =  [0. 0. 0. 0. 0.]


In [ ]:
idades = np.zeros(5, dtype=int)
idades

array([0, 0, 0, 0, 0])

In [ ]:
print('idades =', idades)

idades = [0 0 0 0 0]


In [ ]:
contador = np.array([10,8,6,4,2,0])
print('Contador =', contador)

Contador = [10  8  6  4  2  0]


In [ ]:
n = int(input('Informe o tamanho do vetor: '))
A = np.empty(n)

Informe o tamanho do vetor: 5


In [ ]:
for i in range(0, n):
  A[i] = float(input('Informe o %dº elemento: ' % (i+1)))

Informe o 1º elemento: 1
Informe o 2º elemento: 3
Informe o 3º elemento: 5
Informe o 4º elemento: 7
Informe o 5º elemento: 9


In [ ]:
for i in range(0, n):
  A[i] = A[i] * 3

In [ ]:
print('Imprimindo o vetor na tela...')
for i in range(0, i):
  print('%5.2f' % A[i], end=';')
print

Imprimindo o vetor na tela...
 3.00; 9.00;15.00;21.00;

<function print>

Tentanto replicar o exercício de vetor para a construção de uma matriz

In [49]:
m_quad = input('Você quer uma matriz quadrada? Sim ou Não? ')

l = int(input('Insira o número de linhas: '))
if m_quad == 'Não':
  c = int(input('Insira também o número de colunas: '))
else:
  c = l

Você quer uma matriz quadrada? Sim ou Não? Sim
Insira o número de linhas: 2


In [50]:
A = np.empty([l, c])
print('Sua matriz é:', A.shape)

Sua matriz é: (2, 2)


In [51]:
for i in range(0, l):
  for j in range(0, c):
    z = 'Informe o valor A[%d][%d] ' % (i, j)
    A[i][j] = float(input(z))

Informe o valor A[0][0] 1
Informe o valor A[0][1] 10
Informe o valor A[1][0] 20
Informe o valor A[1][1] 2


In [56]:
print('Imprimindo o vetor na tela...')
for j in range(0, l):
  for i in range(0, c):
    print('%5.3f' % A[j][i], end='  ')
  print()

Imprimindo o vetor na tela...
1.000  10.000  
20.000  2.000  


### 3.2 Strings
Podemos trata-los como vetores de caracteres 

In [36]:
ax = "PLEASE: say, Hello World!"
print('Caracter de índice 1...')
print(ax[1])
print()

Caracter de índice 1...
L



In [37]:
print('Imprime string...')
for x in ax:
  print(x, end='')
print('\n')

Imprime string...
PLEASE: say, Hello World!



In [38]:
print('Imprime string...')
for i in range(0, len(ax), 2):
  print(ax[i], end='')

Imprime string...
PES:sy el ol!

### 3.3 Matrizes
São arranjos de duas dimensões, lembrando que os índices de colunas e linhas começam no 0

In [40]:
nl = int(input('Número de linhas: '))
nc = int(input('Número de colunas: '))

Número de linhas: 2
Número de colunas: 2


In [41]:
A = np.empty((nl, nc))

In [42]:
for i in range(0, nl): # linhas vão de 0 a nl-1
  for j in range(0, nc):
    s = 'Informe o elemento A[%d][%d]: ' % (i, j)
    A[i][j] = float(input(s))

Informe o elemento A[0][0]: -23
Informe o elemento A[0][1]: 5453
Informe o elemento A[1][0]: 1
Informe o elemento A[1][1]: -0.5847


In [43]:
print('Imprime a matriz... \n')
for i in range(0, nl):
  for j in range(0, nc):
    print('%5.1f' % (A[i][j]), end='')
  print() # imprime quebra de linha


Imprime a matriz... 

-23.05453.0
  1.0 -0.6
